stages:
  - test
  - build
  - deploy

realizar_testes:
  stage: test
  image: node:20.7.0-alpine3.17
  before_script:
    - cd app/
    - npm install
  script:
    - npm test
  artifacts:
    when: always
    reports:
      junit: app/junit.xml

build_images:
  stage: build
  needs:
    - realizar_testes
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t laissonbruno/gitlab-cicd-node:1.0 .
    - docker push laissonbruno/gitlab-cicd-node:1.0

deploy_dev:
  stage: deploy
  needs:
    - build_images
  tags:
    - gpc
  script:
    - docker run -d --name nodeapp -p 3000:3000 laissonbruno/gitlab-cicd-node:1.0
    